import { Button, IconButton } from "@chakra-ui/react";
import { useTheme } from "next-themes";
import Head from "next/head";
import { FaBars } from "react-icons/fa";

export default function Home() {
  const { theme, setTheme } = useTheme();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-white dark:bg-black min-h-screen text-black">
        <section className="bg-[url('/bgicons.png')] min-h-screen bg-contain bg-top lg:bg-center lg:bg-cover bg-no-repeat text-primaryText">
          <nav className="font-link text-lg flex justify-between items-center py-4 px-8 md:px-20">
            <div>
              <h1 className="font-medium text-4xl">FarmVest</h1>
            </div>
            <ul className="hidden gap-8 text-lg lg:flex">
              <li>Home</li>
              <li>About</li>
              <li>Features</li>
              <li>How it works</li>
            </ul>
            <div className="text-lg hidden lg:block">
              <a
                href="#"
                className="border-2 border-black py-2 px-6 cursor-pointer text-primary rounded-lg mr-4"
              >
                Sign In
              </a>
              <a
                href="#"
                className="bg-mainGreen py-3 px-6 cursor-pointer text-white rounded-lg shadow-md"
              >
                Get Started
              </a>
            </div>
            <div className="block lg:hidden">
              <IconButton icon={<FaBars />} />
            </div>
          </nav>

          <div className="flex flex-col items-center justify-center pt-24 text-center font-body px-4 lg:px-0">
            <h1 className=" text-4xl md:text-6xl lg:text-7xl font-bold w-full lg:w-4/6 mb-4">
              The easiest and fastest way to
              <span className="text-mainGreen"> Invest </span> in Agriculture
            </h1>
            <p className="w-full lg:w-1/2 text-lg mb-8 dark:text-white">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eu,
              mollis aenean sit dictum tincidunt. Ut arcu, suscipit ac etLorem
              ipsum dolor sit amet.Lorem ipsum dolor sit amet, consectetur
            </p>
            <div className="md:bg-[#E9EBEB] w-full md:w-auto py-2 md:py-4  px-8 md:px-2 rounded-md">
              <input
                type="text"
                placeholder="Enter your email"
                className=" border-2   block md:inline w-full md:w-auto text-center md:border-none md:outline-none md:bg-[#E9EBEB] font-medium text-black py-2 rounded-md md:py-0"
              />
              <a
                href="#"
                className="bg-mainGreen  block md:inline py-3 px-6 cursor-pointer text-white rounded-lg shadow-md mt-2 md:mt-0"
              >
                Get Started
              </a>
            </div>
          </div>
        </section>
      </div>

      <article>
        <Button onClick={() => setTheme(theme === "light" ? "dark" : "light")}>
          {theme === "light" ? (
            <div>
              <FaBars />
            </div>
          ) : (
            "Light"
          )}
        </Button>
      </article>
    </div>
  );
}
